### ISSUE TITLE
expose cameraL, cameraR

### ISSUE THREAD

**Issue by puckey** [mflux/three-vr-viewer#1]
Would it be possible to expose cameraL & cameraR? We are working with the frustum of the camera, which is slightly different for cameraL & cameraR in comparison to the main camera.

**Comment by mflux** [comment]
Hmm.. I looked into this issue and the variables for cameraL and cameraR are protected within VREffect which is what we're using:

https://github.com/mrdoob/three.js/blob/dev/examples/js/effects/VREffect.js

It's a bit out of scope for this lib to be creating custom versions of VREffect. Perhaps you can suggest this to THREE.js repo issues instead? Or make a pull request, it'd be relatively straightforward to modify VREffect to expose the two, and that way you'll have it "for free" here as well.

**Comment by puckey** [comment]
Ahh of course, will do!
